### 年ごとで学校事故で死亡した子ども、障害を負った子どもの推移

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# ファイルパス（Notebookと同じフォルダにある場合）
shougai_path = 'shougai(2025.01.31).xlsx'
sibou_path = 'sibou(2025.01.31).xlsx'

# シート名を指定して読み込む
df_shougai = pd.read_excel(shougai_path, sheet_name='障害見舞金（7682）')
df_sibou = pd.read_excel(sibou_path, sheet_name='死亡見舞金（1151）')

In [3]:
df_sibou

,和暦,給付年度,記号,重複事例,種別,被災学校種,被災学年,性別,場合別1,場合別2,競技種目,通学方法,発生場所1,発生場所2,遊具等,災害発生時の状況
0,平成,17,17死1,17供1,溺死,小,1,男,各教科等,体育（保健体育）,水泳,NaN,学校外（園外）,道路,NaN,体育授業中、近くの温水プールでの水泳学習を終え、準備のできた児童から学校へ戻っていたが、当時...
1,平成,17,17死2,NaN,中枢神経系突然死,小,1,女,各教科等,体育（保健体育）,鉄棒運動,NaN,学校内・校舎外（園内・園舎外）,運動場・校庭（園庭）,鉄棒,体育の授業中、低鉄棒の上に腰をかける体勢から飛び降りる運動をしていた際、鉄棒から前向きに落下...
2,平成,17,17死3,NaN,心臓系突然死,小,6,女,各教科等,体育（保健体育）,短距離走,NaN,学校内・校舎外（園内・園舎外）,運動場・校庭（園庭）,NaN,体育の授業中、運動会の１００メートル走の練習として本生徒が１００mを走った際、ゴールした後に...
3,平成,17,17死4,NaN,心臓系突然死,小,6,男,各教科等,体育（保健体育）,短距離走,NaN,学校内・校舎外（園内・園舎外）,運動場・校庭（園庭）,NaN,体育の時間に、リレー（トラック半周５５ｍ）を自分の走れる速さで走っていたところ、第２コーナー...
4,平成,17,17死5,NaN,心臓系突然死,小,5,女,各教科等,総合的な学習の時間,NaN,NaN,学校内・校舎内（園内・園舎内）,実習実験室,NaN,調理実習中、食器を洗っていた際、突然倒れた。倒れたときは、全身が震えすぐにチアノーゼがあらわ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1146,令和,5,2023死32,NaN,全身打撲,高専,5,男,通学中,下校（降園）中,NaN,鉄道,学校外（園外）,その他,NaN,下校中、激しい腹痛でふらつき、駅のホームから転落したところを電車にひかれ、同日死亡した。
1147,令和,5,2023死33,NaN,頭部外傷,特高,2,男,特別活動（除学校行事）,学級（ホームルーム）活動,NaN,NaN,学校内・校舎内（園内・園舎内）,その他,NaN,学級（ホームルーム）活動中、トイレから帰ってこない本生徒を教員が探したところ、２階ひさしに出...
1148,令和,5,2023死34,NaN,心臓系突然死,特高,2,男,学校行事,修学旅行,NaN,NaN,学校外（園外）,その他,NaN,修学旅行中、２日目の夕方、体調不良のため部屋で休んでいた際、急にチアノーゼの症状が出て呼吸し...
1149,令和,5,2023死35,NaN,窒息死（溺死以外）,保,2,男,保育中,NaN,NaN,NaN,学校内・校舎外（園内・園舎外）,運動場・校庭（園庭）,総合遊具・アスレティック,保育中、園庭の大型遊具で遊んでいた際、遊具内に設置されていた柵と天井の隙間に首が挟まっている...
1150,令和,5,2023死36,NaN,窒息死（溺死以外）,保,1,女,保育中,NaN,NaN,NaN,学校内・校舎内（園内・園舎内）,教室（保育室）,NaN,保育中、保育室で給食のりんごを食べていた際、そしゃく中に眠そうなそぶりが見られたため声を掛け...

In [4]:
def wareki_to_seireki(wareki, year):
    """
    和暦（平成・令和）と年数から西暦に変換
    wareki: '平成' または '令和'
    year: 数値（元年 = 1）
    """
    if wareki == '平成':
        return 1988 + year  # 平成元年 = 1989年
    elif wareki == '令和':
        return 2018 + year  # 令和元年 = 2019年
    else:
        return None  # その他の元号（大正・昭和など）は未対応

In [5]:
# 和暦＋年度 → 西暦の変換
df_shougai['西暦'] = df_shougai.apply(lambda row: wareki_to_seireki(row['和暦'], row['給付年度']), axis=1)
df_sibou['西暦'] = df_sibou.apply(lambda row: wareki_to_seireki(row['和暦'], row['給付年度']), axis=1)

In [7]:
# 西暦列の先頭を確認
print(df_shougai[['和暦', '給付年度', '西暦']].tail())
print(df_sibou[['和暦', '給付年度', '西暦']].tail())

      和暦  給付年度    西暦
7677  令和     5  2023
7678  令和     5  2023
7679  令和     5  2023
7680  令和     5  2023
7681  令和     5  2023
      和暦  給付年度    西暦
1146  令和     5  2023
1147  令和     5  2023
1148  令和     5  2023
1149  令和     5  2023
1150  令和     5  2023

In [9]:
# 死亡と障害の年ごとの件数を数える（西暦を使う）
shougai_counts = df_shougai['西暦'].value_counts().sort_index()
sibou_counts = df_sibou['西暦'].value_counts().sort_index()

In [10]:
df_counts = pd.DataFrame({
    '死亡': sibou_counts,
    '障害': shougai_counts
}).fillna(0).astype(int)

display(df_counts.head())

      死亡   障害
西暦
2005  82  439
2006  74  506
2007  75  497
2008  74  465
2009  68  463

In [11]:
# 年度別の件数をCSVとして保存
df_counts.to_csv('school_accidents_by_year.csv', index_label='年')